name: Github Token Proxy

on:
  push:
    branches:
      - main  # 监听 main 分支的 push 事件
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  get_commits_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch commits
        run: |
          echo "Fetching commits from GitHub API..."
          # 获取最新的 100 次提交的基本信息
          curl -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/${{ github.repository }}/commits?sha=main&per_page=100" > commits_base.json
          echo "Fetched basic commit information."

      - name: Fetch detailed commit data
        run: |
          echo "Fetching detailed commit data..."
          mkdir -p commits_details
          for sha in $(jq -r '.[].sha' commits_base.json); do
            curl -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
                 -H "Accept: application/vnd.github.v3+json" \
                 "https://api.github.com/repos/${{ github.repository }}/commits/$sha" > "commits_details/$sha.json"
          done
          echo "Fetched detailed commit data."

      - name: Combine commit data
        run: |
          echo "Combining commit data..."
          jq -s '[.[][]]' commits_details/*.json > commits.json
          echo "Combined commit data into commits.json."

      - name: Setup Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Switch to gh-pages branch
        run: |
          git checkout --orphan gh-pages
          git reset --hard

      - name: Deploy to GitHub Pages
        run: |
          git add commits.json
          git commit -m "Deploy commits.json to GitHub Pages"
          git push -f origin gh-pages
