name: GitHub API Proxy

on:
  workflow_dispatch:
  repository_dispatch:
    types: [fetch-commits]

jobs:
  fetch_commits:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Token
        run: |
          echo "Fetching commits from GitHub API..."
          curl -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/commits?sha=main&per_page=100 > commits.json

      - name: Check Commits JSON
        run: |
          echo "Checking commits.json..."
          cat commits.json

      - name: Deploy to GitHub Pages
        run: |
          # 确保你使用的是 gh-pages 分支（或者设置你的 GitHub Pages 部署分支）
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout gh-pages || git checkout --orphan gh-pages
          cp commits.json ./commits.json  # 将文件拷贝到 gh-pages 分支
          git add commits.json
          git commit -m "Update commits.json"
          git push origin gh-pages
