name: GitHub API Proxy

on:
  workflow_dispatch:
  repository_dispatch:
    types: [fetch-commits]

jobs:
  fetch_commits:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch Commits
      run: |
        curl -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/${{ github.repository }}/commits?sha=main&per_page=100 > commits.json
    - name: Upload Commits Data
      uses: actions/upload-artifact@v2
      with:
        name: commits-data
        path: commits.json
