name: Generate and Deploy Commits Data

on:
  push:
    branches:
      - main  # 监听 main 分支的 push 事件
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  fetch_commits_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch commits data
        run: |
          echo "Fetching commits from GitHub API..."
          curl -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/commits?sha=main&per_page=100 > commits.json

      - name: Setup Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy to GitHub Pages
        run: |
          git add commits.json
          git commit -m "Update commits data"
          git push origin main
