name: Github Token Proxy

on:
  push:
    branches:
      - main  # 监听 main 分支的 push 事件
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  fetch_token_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete existing commits.json
        run: |
          if [ -f commits.json ]; then
            echo "Deleting existing commits.json..."
            rm commits.json
          fi

      - name: Write REPO_TOKEN to commits.json
        run: |
          echo "Writing REPO_TOKEN to commits.json..."
          echo "${{ secrets.REPO_TOKEN }}" > commits.json

      - name: Setup Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push updated commits.json
        run: |
          git add commits.json
          git commit -m "Add REPO_TOKEN to commits.json"
          git push origin main
