name: Github Token Proxy

on:
  push:
    branches:
      - main  # 监听 main 分支的 push 事件
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  get_commits_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Commits
        run: |
          echo "Fetching commits from GitHub API..."
          curl -v -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/${{ github.repository }}/commits?sha=main&per_page=1000" | tee commits.json

      - name: Fetch Last Modification Times
        run: |
          echo "{}" > last_commit_dates.json
          echo "Fetching file list from GitHub API..."
          
          FILES=$(curl -s -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
                  -H "Accept: application/vnd.github.v3+json" \
                  "https://api.github.com/repos/${{ github.repository }}/git/trees/main?recursive=true" | jq -r '.tree[] | select(.type=="blob") | .path')

          echo "Fetching last commit dates for each file..."
          for file in $FILES; do
            LAST_COMMIT=$(curl -s -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
                        -H "Accept: application/vnd.github.v3+json" \
                        "https://api.github.com/repos/${{ github.repository }}/commits?path=$file&per_page=1" | jq -r '.[0].commit.committer.date')
            jq --arg file "$file" --arg date "$LAST_COMMIT" \
               '. + {($file): $date}' last_commit_dates.json > tmp.json && mv tmp.json last_commit_dates.json
          done

          cat last_commit_dates.json

      - name: Setup Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Switch to gh-pages branch
        run: |
          git checkout --orphan gh-pages
          git reset --hard

      - name: Deploy to GitHub Pages
        run: |
          git add commits.json last_commit_dates.json
          git commit -m "Deploy commits.json and last_commit_dates.json to GitHub Pages"
          git push -f origin gh-pages
